# Generated by Django 5.2.3 on 2025-06-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kitap Adı')),
                ('author', models.CharField(max_length=100, verbose_name='Yazar')),
                ('status', models.CharField(choices=[('to_read', 'Okunacak'), ('reading', 'Okunuyor'), ('read', 'Okundu')], default='to_read', max_length=10, verbose_name='Durum')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sayfa Sayısı')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='Kapak Resmi URL')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Okumaya Başlama Tarihi')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Bitirme Tarihi')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Puan (1-5)')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Değerlendirme')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ['-added_date'],
            },
        ),
    ]
